const ROLE_ADMIN = 'admin';
const ROLE_OWNER = 'owner';
const ROLE_AUDITOR = 'auditor';
const ROLE_BRAND_OWNER = 'brand_owner';
const ROLE_BRAND_AUDITOR = 'brand_auditor';
const ROLE_FRANCHISE_OWNER = 'franchise_owner';

const ADMIN_ROLES = [ROLE_ADMIN, ROLE_BRAND_OWNER, ROLE_FRANCHISE_OWNER];
const BRAND_ROLES = [ROLE_BRAND_OWNER, ROLE_BRAND_AUDITOR];
const FRANCHISE_ROLES = [ROLE_FRANCHISE_OWNER];

module.exports = {
  ROLE_ADMIN,
  ROLE_OWNER,
  ROLE_AUDITOR,
  ROLE_BRAND_OWNER,
  ROLE_BRAND_AUDITOR,
  ROLE_FRANCHISE_OWNER,
  ADMIN_ROLES,
  BRAND_ROLES,
  FRANCHISE_ROLES
};
